package server

// Generated by https://quicktype.io

// Sign
type SignData struct {
	Oper string `json:"oper"`
	User User   `json:"user"`
}

// Room
type RoomData struct {
	Oper string `json:"oper"`
	User User   `json:"user"`
	Room Room   `json:"room"`
}

// Send
type SendData struct {
	Oper string `json:"oper"`
	Uid  int    `json:"uid"`
	Mess string `json:"mess"`
}

// Info
type InfoData struct {
	Oper       string `json:"oper"`
	RoomOrUser string `json:"type"`
	ID         int    `json:"id"`
}

type Room struct {
	Rid   int    `json:"rid"`
	Name  string `json:"name"`
	IsPri bool   `json:"ispri"`
	Pass  string `json:"pass"`
}

type User struct {
	Uid  int    `json:"uid"`
	Name string `json:"name"`
	Pass string `json:"pass"`
}

type Mes struct {
	Ok  bool   `json:"ok"`
	Tip string `json:"tip"`
}
